import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Management task App",
  description: "Generated by create Criston",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Solo deja un favicon y asegúrate que el archivo exista */}
        <link rel="icon" href="/not.png" type="image/png" sizes="32x32" />
        {/* Si no funciona, prueba con favicon.ico: */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer style={{ textAlign: "center", marginTop: "2rem", fontSize: "0.9rem" }}>
          <a
            href="https://www.flaticon.es/iconos-gratis/recordatorio"
            title="recordatorio iconos"
            target="_blank"
            rel="noopener noreferrer"
          >
            Recordatorio iconos creados por Freepik - Flaticon
          </a>
        </footer>
      </body>
    </html>
  );
}

