import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Management task App",
  description: "Generated by create Criston",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Solo deja un favicon y asegúrate que el archivo exista */}
        <link rel="icon" href="/not.png" type="image/png" sizes="32x32" />
        {/* Si no funciona, prueba con favicon.ico: */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </head>
      <body
        className="antialiased"
      >
        {children}
        <footer style={{ textAlign: "center", marginTop: "2rem", fontSize: "0.9rem" }}>
          <a
            href="https://www.flaticon.es/iconos-gratis/recordatorio"
            title="recordatorio iconos"
            target="_blank"
            rel="noopener noreferrer"
          >
          </a>
        </footer>
      </body>
    </html>
  );
}

